title: Jeff Adler
subtitle: Developer | Author | Thought Leader
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website

url: "https://jeff-adler.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact Me
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.png
author: Jeff Adler
author_bio: I am a <strong>Natural Language Processing researcher</strong> turned <strong>Programmatic Ad Specialist</strong> turned <strong>Instructional Designer</strong> turned <strong>Software Developer</strong> writing code built to scale!
author_email: "jeffm.adler@gmail.com"
author_location: Brooklyn, NY
author_website_url: "https://jeff-adler.github.io"
typewrite-text: This is my personal website. Enjoy your stay!

author_work_experiences:
            - company_name: MediaMath
              company_logo: mediamath_small.png
              company_url: http://www.mediamath.com/
              designation: Program Manager, L&D
              description: Designed, Executed, and Managed new employee training programs.
              visibility: true
            - company_name: Semasio
              company_logo: semasio_small.png
              company_url: https://www.semasio.com/
              designation: Client Development Manager
              description: Managed accounts across NA, LATAM, and APAC
              visibility: true

author_education_details:
              - college_logo: fiat-slug.jpg
                college_name: University of California, Santa Cruz
                college_url: https://www.ucsc.edu/
                college_degree: Linguistics
                description: Master of Arts
                visibility: true
              - college_logo: rutgers.png
                college_name: Rutgers University, New Brunswick
                college_url: https://www.rutgers.edu/
                college_degree: Linguistics, Cognitive Science
                description: Bachelor of Arts
                visibility: true

author_project_details:
              - project_thumbnail: heart_headphones.jpg
                project_title: Spotify Dating App
                project_description: A command-line dating app using Spotify API
                project_url: https://github.com/Jeff-Adler/spotify_dating_app
                visibility: true
              - project_thumbnail: hired_img.jpg
                project_title: JobMate
                project_description: A job posting meta-search engine 
                project_url: PLACEHOLDER
                visibility: true

# social links
# twitter_username: johndoe
github_username:  Jeff-Adler
# facebook_username: johndoe
linkedin_username: jeff-adler-8a5400157
# behance_username: johndoe
# instagram_username: johndoe
medium_username: jeffm.adler
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
# formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
